name: TriggerAzurePipeline

# Run this workflow every time a commit gets pushed to master branch
on:
  push:
    branches:
    - master

jobs:
    TriggerAzurePipeline:
        name: Call Azure Pipeline
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/namantraining/MyFirstProject
            azure-pipeline-name: 'MyFirstBuildDefinition'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
