name: learn-github-actions
run-name: ${{ github.actor }} learning github actions
on: workflow_dispatch
jobs:
  build-my-code:
    runs-on: windows-2019 
    steps:
    - name: check out code
      uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore nuget packages
      run: nuget restore WebApplication/WebApplication.sln
      
    - name: Build my Web code
      run: msbuild WebApplication/WebApplication.sln /p:Configuration=Release /p:DeployTarget=Package /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeployOnBuild=true
  
    - name: Build my SQL code
      run: msbuild WebApplication/Database1/Database1.sqlproj
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: published_webapp
        path: bin\Release\Publish
        
  
