name: va

on:
  workflow_dispatch

env:
  workflow_variable_day: Tuesday
  workflow_variable_password: ${{ secrets.PASSWORD }}

jobs:
  variable_example:
    runs-on: ubuntu-latest
    env:
      job_variable: Hello
    steps:
      - name: "Greet Ramesh"
        env:
          step_variable: Ramesh
        run: echo "$job_variable $step_variable. Today is $workflow_variable_day"        
      - name: "Password"
        run: echo "$workflow_variable_password"
