name: TriggerAzurePipeline

on: workflow_dispatch

jobs:
    TriggerAzurePipeline:
        name: Call Azure Pipeline from Github Actions
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
              azure-devops-project-url: https://dev.azure.com/namantraining/MyFirstProject
              azure-pipeline-name: 'MyFirstBuildDefinition'
              azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
			  
